name: Quartus II Compilation

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - 'flash.sh'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - 'flash.sh'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}:${{ github.ref }}
  cancel-in-progress: true

jobs:
  synthesis:
    runs-on: ubuntu-latest
    container: raetro/quartus:13.0sp1
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup and Synthesis
        run: ./compile.sh

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: artifacts.zip
          path: |
            db/
            compile/
            logs/
          if-no-files-found: ignore